### ISSUE TITLE
api: support gRPC and provide SDKs

### ISSUE THREAD

**Issue by zhenghaoz** [zhenghaoz/gorse#344]
Compare to exited RESTful API, gRPC is more efficient for communications among servers.

## Design

For each API, move current implementation to a shared handler, and call this shared handler from RESTful API handler as well as gRPC API handler. 

```
┌───────────┐ ┌───────────┐
│RESTful API│ │ gRPC API  │
└─────────┬─┘ └─┬─────────┘
          │     │
        ┌─▼─────▼─┐
        │ Handler │
        └─────────┘
```

## Tasks

- [ ] gRPC APIs
- [ ] Gorse Go SDK
- [ ] Gorse Java SDK
- [ ] Gorse Rust SDK
- [ ] Gorse Python SDK
- [ ] Gorse Node.js SDK

**Comment by bilinxing** [comment]
+1
